# permissions for end users to edit entraappregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: entra-governance
    app.kubernetes.io/managed-by: kustomize
  name: entraappregistration-editor-role
rules:
- apiGroups:
  - iam.entra.governance.com
  resources:
  - entraappregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.entra.governance.com
  resources:
  - entraappregistrations/status
  verbs:
  - get
